jobs:
  test:
    executor:
      name: node/default
      tag: '13.14'
    steps:
      - checkout
      - node/install:
          install-yarn: true
          install-npm: false
      - node/install-packages:
          pkg-manager: yarn
      - run:
          command: yarn test
          name: Run YARN tests

version: 2.1
orbs:
  node: circleci/node@4.1.0
workflows:
  node-tests:
    jobs:
      - test
